name: Metrics
on:
  # Schedule updates (runs every day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Allows you to run the action manually from the Actions tab
  workflow_dispatch:
  # Runs when you push changes to the main branch
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: afnan-nex
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_gists: yes
          plugin_habits: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
